spring:
  cloud:
    stream:
      function:
        # 这里的名称与AppConfig中bean的名称要保持一致
        definition: pkSlowSinkX
      bindings:
        # 中划线以及后面内容是固定的
        pkSlowSourceX-out-0:
          destination: pkslow-topic-single
          consumer:
            # 如果最大尝试次数为1，即不重试
            # 默认是做3次尝试
            max-attempts: 5
            # 两次重试之间的初始间隔
            backOffInitialInterval: 2000
            # 重试最大间隔
            backOffMaxInterval: 10000
            # 每次重试后，间隔时间乘以的系数
            backOffMultiplier: 2
            # 如果某个异常你不想重试，写在这里
            retryableExceptions:
              java.lang.IllegalArgumentException: false
        pkSlowSinkX-in-0:
          destination: pkslow-topic-single
      poller:
        fixed-delay: 5000  # 固定时间发送一条消息
      kafka:
        binder:
          brokers: 192.168.99.51:9092
          auto-create-topics: true
          required-acks: 1
          replication-factor: 1
      # 手动发送消息
#      output-bindings: pkSlowSourceX-out-0