spring:
  cloud:
    function:
      # 这里的名称与AppConfig中bean的名称要保持一致
      definition: pkSlowSourceX; pkSlowSinkX
    stream:
      bindings:
        # 中划线以及后面内容是固定的
        pkSlowSourceX-out-0:
          destination: pkslow-topic-multi
          binder: myKafka1
        pkSlowSinkX-in-0:
          destination: pkslow-topic-multi
          binder: myKafka1
      poller:
        fixed-delay: 2000  # 固定时间发送一条消息
      # 如果你项目里只对接一个中间件，那么不用定义binders
      binders:
        myKafka1:
          type: kafka
          environment:
            spring:
              kafka:
                #bootstrap-servers: 192.168.99.51:9092
                bootstrap-servers: 127.0.0.1:9092
                auto-create-topics: true
                required-acks: 1
                replication-factor: 1