--- # brokers config
spring:
  cloud:
    stream:
      binders:
        myKafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: 192.168.99.51:8989
# spring cloud 2021.0.4 版本配置
#spring:
#  cloud:
#    stream:
#      binders:
#        myKafka1:
#          type: kafka
#          environment:
#             spring.kafka.bootstrap-servers: 192.168.99.51:8989
--- # ssl config
spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            security.protocol: SSL
            ssl.endpoint.identification.algorithm: ""
            ssl.truststore.location: "classpath:client.truststore.jks"
            ssl.truststore.password: "hello123"
--- # function config
spring:
  cloud:
    # 注意 function 节点与stream 同级，而非子节点
    function:
      definition: helloFunc;
--- # binding config
spring:
  cloud:
    stream:
      bindings:
        helloFunc-in-0:
          destination: hello-topic
          group: hello-local-test-10
          binder: myKafka1
          consumer:
            batch-mode: true
        helloFunc-out-0:
          destination: hello-topic
          group: hello-local-test-10
          binder: myKafka1
          consumer:
            batch-mode: true
