--- # common config
spring:
  cloud:
    stream:
      binders:
        myKafka1:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: 192.168.99.51:8989
      kafka:
        binder:
          configuration:
            security.protocol: SSL
            ssl.endpoint.identification.algorithm: ""
            ssl.truststore.location: "classpath:client.truststore.jks"
            ssl.truststore.password: "hello123"
--- # function config
spring:
  cloud:
    function:
      definition: helloFunc;
--- # binding config
spring:
  cloud:
    stream:
      bindings:
        helloFunc-in-0:
          destination: hello-topic
          group: hello-local-test-10
          binder: myKafka1
          consumer:
            batch-mode: true
